//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFormsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public agent()
        {
            this.agentbalances = new HashSet<agentbalance>();
            this.salesas = new HashSet<salesa>();
        }
    
        public int id { get; set; }
        public string agent_name { get; set; }
        public string phone { get; set; }
        public string agent_address { get; set; }
    
        public virtual ICollection<agentbalance> agentbalances { get; set; }
        public virtual ICollection<salesa> salesas { get; set; }
    }
}
