//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFormsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashbook
    {
        public cashbook()
        {
            this.ledgers = new HashSet<ledger>();
        }
    
        public Nullable<System.DateTime> date { get; set; }
        public int customerid { get; set; }
        public string name { get; set; }
        public int receiptno { get; set; }
        public decimal amount { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<ledger> ledgers { get; set; }
    }
}
