//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFormsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config
    {
        public config()
        {
            this.solds = new HashSet<sold>();
            this.soldas = new HashSet<solda>();
            this.soldcs = new HashSet<soldc>();
            this.stocks = new HashSet<stock>();
        }
    
        public int config_id { get; set; }
        public string product_name { get; set; }
        public string features { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> agentprice { get; set; }
    
        public virtual product product { get; set; }
        public virtual ICollection<sold> solds { get; set; }
        public virtual ICollection<solda> soldas { get; set; }
        public virtual ICollection<soldc> soldcs { get; set; }
        public virtual ICollection<stock> stocks { get; set; }
    }
}
