//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFormsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ledger
    {
        public Nullable<System.DateTime> cashdate { get; set; }
        public Nullable<System.DateTime> invoicedate { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string company { get; set; }
        public Nullable<int> receiptno { get; set; }
        public Nullable<decimal> amountpaid { get; set; }
        public string invoice_no { get; set; }
        public Nullable<decimal> grossamount { get; set; }
        public Nullable<decimal> discountamount { get; set; }
        public Nullable<decimal> netamount { get; set; }
        public Nullable<decimal> discountpercent { get; set; }
        public Nullable<decimal> debitcredit { get; set; }
        public int transactionid { get; set; }
    
        public virtual cashbook cashbook { get; set; }
    }
}
