//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFormsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.configs = new HashSet<config>();
        }
    
        public string product_name { get; set; }
        public string category_name { get; set; }
        public string company_name { get; set; }
    
        public virtual category category { get; set; }
        public virtual company company { get; set; }
        public virtual ICollection<config> configs { get; set; }
    }
}
