//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFormsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public string C_name { get; set; }
        public string username { get; set; }
        public string C_password { get; set; }
        public string contactno { get; set; }
        public string joiningdate { get; set; }
        public string C_role { get; set; }
    }
}
