//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqFormsApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shopEntities : DbContext
    {
        public shopEntities()
            : base("name=shopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<agentbalance> agentbalances { get; set; }
        public DbSet<agent> agents { get; set; }
        public DbSet<balance> balances { get; set; }
        public DbSet<cashbook> cashbooks { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<company> companies { get; set; }
        public DbSet<config> configs { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<ledger> ledgers { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<registration> registrations { get; set; }
        public DbSet<@return> returns { get; set; }
        public DbSet<sale> sales { get; set; }
        public DbSet<salesa> salesas { get; set; }
        public DbSet<salesc> salescs { get; set; }
        public DbSet<sold> solds { get; set; }
        public DbSet<solda> soldas { get; set; }
        public DbSet<soldc> soldcs { get; set; }
        public DbSet<stock> stocks { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<Cust> Custs { get; set; }
    }
}
